### ISSUE TITLE
reusing platformOptions object doesn't set type

### ISSUE THREAD

**Issue by sandikbarr** [bellicapax/toybox#7]
Should be able to open my workspace at https://ide.c9.io/sandikbarr/sugar-cubed-lessons

There is an example showing this issue at `/challenges/easy-02_fly-trap/fly-trap.js`. It re-uses the same object to create many platforms. Only the first platform has the type set correctly.

Looks like the bug is on platform.js line 28. ` if (typeof(platformOptions.spriteName) == "undefined")`. Maybe if the condition could be to check if type was defined and valid.

**Comment by Ayolland** [comment]
Refactored this plugin so that using the same options object repeatedly will result in platforms of the same type.
